[build]
  command = "php artisan export"
  publish = "export"
  
[build.environment]
  PHP_VERSION = "8.1"

[context.production.environment]
  APP_ENV = "production"
  APP_KEY = "base64:gVUiIj11FkKIirGrweiOabCwthN6SVbmWg8/yQOXY8c="